FROM 145292399405.dkr.ecr.eu-north-1.amazonaws.com/patrick-pfe:ia-service

WORKDIR /app

COPY app/ ./app/
COPY alembic.ini .
COPY migrations/ ./migrations/

CMD ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 2"]
