"""add_column_analysis_table

Revision ID: 0774812a95a5
Revises: 3c71a34c353b
Create Date: 2026-03-07 15:40:04.562992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0774812a95a5'
down_revision: Union[str, Sequence[str], None] = '3c71a34c353b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('identifiers', sa.JSON(), nullable=True),
    sa.Column('temporal', sa.JSON(), nullable=True),
    sa.Column('geographic', sa.JSON(), nullable=True),
    sa.Column('other', sa.JSON(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('dashboard_columns', sa.JSON(), nullable=True),
    sa.Column('primary_metric', sa.String(), nullable=True),
    sa.Column('analysis_method', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('total_relationships', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    op.create_index(op.f('ix_column_analysis_id'), 'column_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_analysis_id'), table_name='column_analysis')
    op.drop_table('column_analysis')
    # ### end Alembic commands ###
