"""add cleaning profile tables

Revision ID: 3c71a34c353b
Revises: 67f37e9061e3
Create Date: 2026-03-03 20:07:50.387123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c71a34c353b'
down_revision: Union[str, Sequence[str], None] = '67f37e9061e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('handle_missing', sa.String(), nullable=True),
    sa.Column('missing_fill_strategy', sa.String(), nullable=True),
    sa.Column('missing_fill_value', sa.String(), nullable=True),
    sa.Column('remove_duplicates', sa.Boolean(), nullable=True),
    sa.Column('duplicate_subset', sa.JSON(), nullable=True),
    sa.Column('fix_data_types', sa.Boolean(), nullable=True),
    sa.Column('detect_outliers', sa.Boolean(), nullable=True),
    sa.Column('outlier_method', sa.String(), nullable=True),
    sa.Column('outlier_threshold', sa.Float(), nullable=True),
    sa.Column('outlier_action', sa.String(), nullable=True),
    sa.Column('strip_whitespace', sa.Boolean(), nullable=True),
    sa.Column('standardize_text', sa.Boolean(), nullable=True),
    sa.Column('standardize_dates', sa.Boolean(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('normalize_numeric', sa.Boolean(), nullable=True),
    sa.Column('normalization_method', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_profiles_id'), 'cleaning_profiles', ['id'], unique=False)
    op.create_table('cleaning_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('operations_performed', sa.JSON(), nullable=True),
    sa.Column('rows_before', sa.Integer(), nullable=True),
    sa.Column('rows_after', sa.Integer(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('missing_values_handled', sa.Integer(), nullable=True),
    sa.Column('outliers_detected', sa.Integer(), nullable=True),
    sa.Column('data_types_fixed', sa.Integer(), nullable=True),
    sa.Column('cleaning_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['cleaning_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_logs_id'), 'cleaning_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cleaning_logs_id'), table_name='cleaning_logs')
    op.drop_table('cleaning_logs')
    op.drop_index(op.f('ix_cleaning_profiles_id'), table_name='cleaning_profiles')
    op.drop_table('cleaning_profiles')
    # ### end Alembic commands ###
